verb1 = input("Type a verb with ing here: ")
adjective1 = input("Type a Adjective with y in it here: ")
noun1 = input("Type a person's name here: ")
noun2 = input("Type a secound noun here: ")
adjective2 = input("Type a adjective here with a ly: ")
verb3 = input("Type a verb that ends with ing: ")
noun3 = input("Type your name: ")
verb4 = input("Type a adjective: ")
print("It was a dark and "+adjective1+" night. It was at "+noun1+"'s House. They were "+verb1+". Then they threw a "+verb4+" "+noun2+" at you. You "+adjective2+" dodged it. You said to "+noun1+", 'Why "+noun1+"!' They respond with 'You suck "+noun3+"!' Suddenly, you see some people "+verb3)