verb1 = input("Type a verb with ing here: ")
adjective1 = input("Type a Adjective with y in it here: ")
noun1 = input("Type a person's name here: ")
noun2 = input("Type a secound noun here: ")
verb2 = input("Type a secound verb here with a ly: ")
verb3 = input("Type a verb that ends with ed")
print("It was a dark and "+adjective1+" night. It was at "+noun1+"'s House. They were "+verb1+". Then they threw a "+noun2+" at you. You "+verb2+" dodged it. You "+verb3+" at "+noun1+", 'Why "+noun1+"!'")